--- #YAML:1.0
name:               Judy-HS
version:            0.01
abstract:           Library for creating and accessing a dynamic array, using an array-of-bytes of Length as an Index and a word as a Value. 
author:
    - Joshua ben Jore <jjore@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
